services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10"
      USERNAME: "SALMAN"
      PASSWORD: "Salman123"
      RAM_SIZE: "32G"
      CPU_CORES: "8"
      DISK_SIZE: "300G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp

    stop_grace_period: 2m

